# Copyright (c) 2024, Itential, Inc
# GNU General Public License v3.0+ (see LICENSE or https://www.gnu.org/licenses/gpl-3.0.txt)
---

- name: Download Prometheus
  ansible.builtin.uri:
    creates: /opt/prometheus/prometheus.tar.gz
    dest: /opt/prometheus/prometheus.tar.gz
    owner: "{{ prometheus_user }}"
    group: "{{ prometheus_group }}"
    mode: "0755"
    url: "{{ prometheus_download_url }}"

- name: Untar prometheus    
  ansible.builtin.unarchive:
    src: /opt/prometheus/prometheus.tar.gz
    dest: /opt/prometheus
    remote_src: true
    owner: "{{ prometheus_user }}"
    group: "{{ prometheus_group }}"
    mode: "0755"
    extra_opts:
      - --strip-components=1

- name: Create prometheus config file
  ansible.builtin.template:
    src: prometheus-config.yml.j2
    dest: /opt/prometheus/prometheus-config.yml
    owner: "{{ prometheus_user }}"
    group: "{{ prometheus_group }}"
    mode: "0644"
    lstrip_blocks: true

- name: Create systemd service file
  ansible.builtin.template:
    src: prometheus.service.j2
    dest: /usr/lib/systemd/system/prometheus.service
    mode: "0644"
    lstrip_blocks: true

- name: Start prometheus as a systemd service
  ansible.builtin.systemd:
    name: prometheus
    enabled: true
    daemon_reload: true
    state: restarted