# Copyright (c) 2024, Itential, Inc
# GNU General Public License v3.0+ (see LICENSE or https://www.gnu.org/licenses/gpl-3.0.txt)
---
- name: Download prometheus mongo-exporter
  ansible.builtin.uri:
    creates: "{{ prometheus_dir }}/mongo-exporter.tar.gz"
    dest: "{{ prometheus_dir }}/mongo-exporter.tar.gz"
    owner: "{{ prometheus_user }}"
    group: "{{ prometheus_group }}"
    mode: "0755"
    url: "{{ prometheus_mongo_exporter_download_url }}"

- name: Untar mongo exporter
  ansible.builtin.unarchive:
    src: "{{ prometheus_dir }}/mongo-exporter.tar.gz"
    dest: "{{ prometheus_dir }}"
    remote_src: true
    owner: "{{ prometheus_user }}"
    group: "{{ prometheus_group }}"
    mode: "0755"
    extra_opts:
      - --strip-components=1

- name: Create mongo exporter systemd file
  ansible.builtin.template:
    src: mongo_exporter.service.j2
    dest: /usr/lib/systemd/system/mongo_exporter.service
    owner: "{{ prometheus_user }}"
    group: "{{ prometheus_group }}"
    mode: "0644"
    lstrip_blocks: true

- name: Start the mongo expoter as a systemd service
  ansible.builtin.systemd:
    name: mongo_exporter
    enabled: true
    daemon_reload: true
    state: restarted

- name: Remove the downloaded tar file
  ansible.builtin.file:
    path: "{{ prometheus_dir }}/mongo-exporter.tar.gz"
    state: absent
