# Copyright (c) 2024, Itential, Inc
# GNU General Public License v3.0+ (see LICENSE or https://www.gnu.org/licenses/gpl-3.0.txt)
---
rabbitmq_server_repo_baseurl: "https://packagecloud.io/rabbitmq/rabbitmq-server/el/$releasever/$basearch"
rabbitmq_erlang_repo_baseurl: "https://packagecloud.io/rabbitmq/erlang/el/$releasever/$basearch"
